package main

import "core:fmt"
import "core:log"
import "core:mem"
import "core:os"
import "core:strings"

import sdl "vendor:sdl3"

WIDTH :: 800
HEIGHT :: 600

BG_COLOR :: sdl.FColor{0.05, 0.05, 0.09, 1}
DEBUG :: true
PLATFORM :: "METAL"
// Must match shaders/triangle.slang VSIn and the pipeline vertex attributes.
Vertex :: struct {
	pos:   [2]f32,
	color: [4]f32,
}

VERTICES := []Vertex {
	{pos = {-0.7, -0.7}, color = {0.95, 0.25, 0.25, 1}},
	{pos = {0.7, -0.7}, color = {0.25, 0.95, 0.25, 1}},
	{pos = {0.0, 0.7}, color = {0.25, 0.25, 0.95, 1}},
}

r: struct {
	window:   ^sdl.Window,
	device:   ^sdl.GPUDevice,
	pipeline: ^sdl.GPUGraphicsPipeline,
	vbo:      ^sdl.GPUBuffer,
}

fail :: proc(msg: cstring) -> ! {
	fmt.eprintfln("%s", msg)
	os.exit(1)
}

load_shader :: proc(
	code: []u8,
	format: sdl.GPUShaderFormat,
	stage: sdl.GPUShaderStage,
	entrypoint: cstring,
) -> ^sdl.GPUShader {
	info := sdl.GPUShaderCreateInfo {
		code_size            = len(code),
		code                 = raw_data(code),
		entrypoint           = entrypoint,
		format               = format,
		stage                = stage,
		num_samplers         = 0,
		num_storage_textures = 0,
		num_storage_buffers  = 0,
		num_uniform_buffers  = 0,
	}
	shader := sdl.CreateGPUShader(r.device, info)
	if shader == nil {
		fail(sdl.GetError())
	}
	return shader
}

// Compiles the shaders (embedded via #load, generated by `make shaders`)
// and creates the graphics pipeline.
renderer_init :: proc(window: ^sdl.Window) {
	r.window = window

	// Both formats requested; which one SDL actually uses depends on the
	// platform driver (Metal on macOS, Vulkan elsewhere).
	r.device = sdl.CreateGPUDevice({.MSL, .SPIRV}, true, nil)
	if r.device == nil {
		fail(sdl.GetError())
	}
	if !sdl.ClaimWindowForGPUDevice(r.device, window) {
		fail(sdl.GetError())
	}

	vert_code := #load("../shaders/generated/triangle.vert.msl")
	frag_code := #load("../shaders/generated/triangle.frag.msl")
	format := sdl.GPUShaderFormat{.MSL}

	if strings.starts_with(string(sdl.GetGPUDeviceDriver(r.device)), "vulkan") {
		vert_code = #load("../shaders/generated/triangle.vert.spv")
		frag_code = #load("../shaders/generated/triangle.frag.spv")
		format = {.SPIRV}
	}

	vert_shader := load_shader(vert_code, format, .VERTEX, "vertexMain")
	frag_shader := load_shader(frag_code, format, .FRAGMENT, "pixelMain")
	defer {
		sdl.ReleaseGPUShader(r.device, vert_shader)
		sdl.ReleaseGPUShader(r.device, frag_shader)
	}

	vertex_attrs := []sdl.GPUVertexAttribute {
		{location = 0, buffer_slot = 0, format = .FLOAT2, offset = u32(offset_of(Vertex, pos))},
		{location = 1, buffer_slot = 0, format = .FLOAT4, offset = u32(offset_of(Vertex, color))},
	}
	vertex_buffers := []sdl.GPUVertexBufferDescription {
		{slot = 0, pitch = u32(size_of(Vertex)), input_rate = .VERTEX, instance_step_rate = 0},
	}

	color_target := sdl.GPUColorTargetDescription {
		format = sdl.GetGPUSwapchainTextureFormat(r.device, window),
	}

	r.pipeline = sdl.CreateGPUGraphicsPipeline(
		r.device,
		sdl.GPUGraphicsPipelineCreateInfo {
			vertex_shader = vert_shader,
			fragment_shader = frag_shader,
			vertex_input_state = sdl.GPUVertexInputState {
				num_vertex_buffers = u32(len(vertex_buffers)),
				vertex_buffer_descriptions = raw_data(vertex_buffers),
				num_vertex_attributes = u32(len(vertex_attrs)),
				vertex_attributes = raw_data(vertex_attrs),
			},
			primitive_type = .TRIANGLELIST,
			rasterizer_state = sdl.GPURasterizerState{fill_mode = .FILL, cull_mode = .NONE},
			target_info = sdl.GPUGraphicsPipelineTargetInfo {
				num_color_targets = 1,
				color_target_descriptions = &color_target,
			},
		},
	)
	if r.pipeline == nil {
		fail(sdl.GetError())
	}

	r.vbo = upload_vertices(VERTICES)
}

// Creates a GPU vertex buffer and uploads the data through a transfer buffer.
upload_vertices :: proc(vertices: []Vertex) -> ^sdl.GPUBuffer {
	size := u32(len(vertices) * size_of(Vertex))

	vbo := sdl.CreateGPUBuffer(r.device, sdl.GPUBufferCreateInfo{usage = {.VERTEX}, size = size})
	if vbo == nil {
		fail(sdl.GetError())
	}

	transfer := sdl.CreateGPUTransferBuffer(
		r.device,
		sdl.GPUTransferBufferCreateInfo{usage = .UPLOAD, size = size},
	)
	if transfer == nil {
		fail(sdl.GetError())
	}
	defer sdl.ReleaseGPUTransferBuffer(r.device, transfer)

	mapped := sdl.MapGPUTransferBuffer(r.device, transfer, false)
	mem.copy(mapped, raw_data(vertices), int(size))
	sdl.UnmapGPUTransferBuffer(r.device, transfer)

	cmd := sdl.AcquireGPUCommandBuffer(r.device)
	copy_pass := sdl.BeginGPUCopyPass(cmd)
	sdl.UploadToGPUBuffer(
		copy_pass,
		sdl.GPUTransferBufferLocation{transfer_buffer = transfer, offset = 0},
		sdl.GPUBufferRegion{buffer = vbo, offset = 0, size = size},
		false,
	)
	sdl.EndGPUCopyPass(copy_pass)
	if !sdl.SubmitGPUCommandBuffer(cmd) {
		fail(sdl.GetError())
	}

	return vbo
}

frame :: proc() {
	cmd := sdl.AcquireGPUCommandBuffer(r.device)

	swapchain: ^sdl.GPUTexture
	if !sdl.WaitAndAcquireGPUSwapchainTexture(cmd, r.window, &swapchain, nil, nil) {
		_ = sdl.CancelGPUCommandBuffer(cmd)
		return
	}
	if swapchain == nil { 	// Window minimized/hidden; present nothing.
		_ = sdl.SubmitGPUCommandBuffer(cmd)
		return
	}

	color_target := sdl.GPUColorTargetInfo {
		texture     = swapchain,
		load_op     = .CLEAR,
		clear_color = BG_COLOR,
		store_op    = .STORE,
	}

	pass := sdl.BeginGPURenderPass(cmd, &color_target, 1, nil)
	sdl.BindGPUGraphicsPipeline(pass, r.pipeline)
	binding := sdl.GPUBufferBinding {
		buffer = r.vbo,
		offset = 0,
	}
	sdl.BindGPUVertexBuffers(pass, 0, &binding, 1)
	sdl.DrawGPUPrimitives(pass, 3, 1, 0, 0)
	sdl.EndGPURenderPass(pass)

	if !sdl.SubmitGPUCommandBuffer(cmd) {
		fail(sdl.GetError())
	}
}

main :: proc() {
	if !sdl.Init(sdl.INIT_VIDEO) {
		fail(sdl.GetError())
	}
	defer sdl.Quit()

	r.window = sdl.CreateWindow("Cubes", WIDTH, HEIGHT, sdl.WINDOW_RESIZABLE)
	if r.window == nil {
		fail(sdl.GetError())
	}
	defer sdl.DestroyWindow(r.window)

	renderer_init(r.window)
	defer {
		_ = sdl.WaitForGPUIdle(r.device)
		if r.vbo != nil do sdl.ReleaseGPUBuffer(r.device, r.vbo)
		if r.pipeline != nil do sdl.ReleaseGPUGraphicsPipeline(r.device, r.pipeline)
		sdl.DestroyGPUDevice(r.device)
	}

	event_loop: for {
		event: sdl.Event
		for sdl.PollEvent(&event) {
			#partial switch event.type {
			case .QUIT:
				break event_loop
			}
		}
		frame()
	}
}
