// Generated by goose/tools/build. Do not edit.
package defaults

import goose "../../goose"

DEFAULT_UNLIT_COLOR_VERTEX_CODE :: #load("generated/default_unlit_color.vert.msl")

DEFAULT_UNLIT_COLOR_VERTEX_SAMPLERS :: 0
DEFAULT_UNLIT_COLOR_VERTEX_STORAGE_TEXTURES :: 0
DEFAULT_UNLIT_COLOR_VERTEX_STORAGE_BUFFERS :: 0
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BUFFERS :: 1

Default_Unlit_Color_Vertex_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
	tint: [4]f32,
}

#assert(offset_of(Default_Unlit_Color_Vertex_Uniforms, mvp) == 0)
#assert(offset_of(Default_Unlit_Color_Vertex_Uniforms, tint) == 64)
#assert(size_of(Default_Unlit_Color_Vertex_Uniforms) == 80)

Default_Unlit_Color_Vertex_Uniform_Block :: struct #max_field_align(16) {
	data: Default_Unlit_Color_Vertex_Uniforms,
}

#assert(offset_of(Default_Unlit_Color_Vertex_Uniform_Block, data) == 0)
#assert(size_of(Default_Unlit_Color_Vertex_Uniform_Block) == 80)

DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SLOT :: 0
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SPACE :: 0
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_BINDING :: 0
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_COUNT :: 1
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SIZE :: 80
DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Vertex,
	location = {space = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SPACE, binding = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_BINDING, slot = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SLOT, count = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_COUNT},
	size = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SIZE,
}

default_unlit_color_vertex_attributes :: proc($Vertex: typeid) -> [1]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
	}
}

DEFAULT_UNLIT_COLOR_VERTEX_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Vertex, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 80},
}

default_unlit_color_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "default_unlit_color.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(DEFAULT_UNLIT_COLOR_VERTEX_CODE), size = len(DEFAULT_UNLIT_COLOR_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = DEFAULT_UNLIT_COLOR_VERTEX_SAMPLERS,
			storage_textures = DEFAULT_UNLIT_COLOR_VERTEX_STORAGE_TEXTURES,
			storage_buffers = DEFAULT_UNLIT_COLOR_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = DEFAULT_UNLIT_COLOR_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {data = &DEFAULT_UNLIT_COLOR_VERTEX_BINDINGS[0], count = len(DEFAULT_UNLIT_COLOR_VERTEX_BINDINGS)},
	}
}

DEFAULT_UNLIT_COLOR_FRAGMENT_CODE :: #load("generated/default_unlit_color.frag.msl")

DEFAULT_UNLIT_COLOR_FRAGMENT_SAMPLERS :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_STORAGE_TEXTURES :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_STORAGE_BUFFERS :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BUFFERS :: 1

Default_Unlit_Color_Fragment_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
	tint: [4]f32,
}

#assert(offset_of(Default_Unlit_Color_Fragment_Uniforms, mvp) == 0)
#assert(offset_of(Default_Unlit_Color_Fragment_Uniforms, tint) == 64)
#assert(size_of(Default_Unlit_Color_Fragment_Uniforms) == 80)

Default_Unlit_Color_Fragment_Uniform_Block :: struct #max_field_align(16) {
	data: Default_Unlit_Color_Fragment_Uniforms,
}

#assert(offset_of(Default_Unlit_Color_Fragment_Uniform_Block, data) == 0)
#assert(size_of(Default_Unlit_Color_Fragment_Uniform_Block) == 80)

DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SLOT :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SPACE :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_BINDING :: 0
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_COUNT :: 1
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SIZE :: 80
DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Fragment,
	location = {space = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SPACE, binding = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_BINDING, slot = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SLOT, count = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_COUNT},
	size = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SIZE,
}

DEFAULT_UNLIT_COLOR_FRAGMENT_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Fragment, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 80},
}

default_unlit_color_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "default_unlit_color.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(DEFAULT_UNLIT_COLOR_FRAGMENT_CODE), size = len(DEFAULT_UNLIT_COLOR_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = DEFAULT_UNLIT_COLOR_FRAGMENT_SAMPLERS,
			storage_textures = DEFAULT_UNLIT_COLOR_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = DEFAULT_UNLIT_COLOR_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = DEFAULT_UNLIT_COLOR_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {data = &DEFAULT_UNLIT_COLOR_FRAGMENT_BINDINGS[0], count = len(DEFAULT_UNLIT_COLOR_FRAGMENT_BINDINGS)},
	}
}

