// Generated by goose/tools/build. Do not edit.
package defaults

import goose "../../goose"

DEFAULT_TEXTURED_VERTEX_CODE :: #load("generated/default_textured.vert.msl")

DEFAULT_TEXTURED_VERTEX_SAMPLERS :: 0
DEFAULT_TEXTURED_VERTEX_STORAGE_TEXTURES :: 0
DEFAULT_TEXTURED_VERTEX_STORAGE_BUFFERS :: 0
DEFAULT_TEXTURED_VERTEX_UNIFORM_BUFFERS :: 1

Default_Textured_Vertex_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
}

#assert(offset_of(Default_Textured_Vertex_Uniforms, mvp) == 0)
#assert(size_of(Default_Textured_Vertex_Uniforms) == 64)

Default_Textured_Vertex_Uniform_Block :: struct #max_field_align(16) {
	data: Default_Textured_Vertex_Uniforms,
}

#assert(offset_of(Default_Textured_Vertex_Uniform_Block, data) == 0)
#assert(size_of(Default_Textured_Vertex_Uniform_Block) == 64)

DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SLOT :: 0
DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SPACE :: 0
DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_BINDING :: 0
DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_COUNT :: 1
DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SIZE :: 64
DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Vertex,
	location = {space = DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SPACE, binding = DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_BINDING, slot = DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SLOT, count = DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_COUNT},
	size = DEFAULT_TEXTURED_VERTEX_UNIFORM_BLOCK_SIZE,
}

default_textured_vertex_attributes :: proc($Vertex: typeid) -> [3]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .Float4, offset = u32(offset_of(Vertex, color))},
		{location = 2, format = .Float2, offset = u32(offset_of(Vertex, uv))},
	}
}

DEFAULT_TEXTURED_VERTEX_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Vertex, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 64},
}

default_textured_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "default_textured.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(DEFAULT_TEXTURED_VERTEX_CODE), size = len(DEFAULT_TEXTURED_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = DEFAULT_TEXTURED_VERTEX_SAMPLERS,
			storage_textures = DEFAULT_TEXTURED_VERTEX_STORAGE_TEXTURES,
			storage_buffers = DEFAULT_TEXTURED_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = DEFAULT_TEXTURED_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {data = &DEFAULT_TEXTURED_VERTEX_BINDINGS[0], count = len(DEFAULT_TEXTURED_VERTEX_BINDINGS)},
	}
}

DEFAULT_TEXTURED_FRAGMENT_CODE :: #load("generated/default_textured.frag.msl")

DEFAULT_TEXTURED_FRAGMENT_SAMPLERS :: 1
DEFAULT_TEXTURED_FRAGMENT_STORAGE_TEXTURES :: 0
DEFAULT_TEXTURED_FRAGMENT_STORAGE_BUFFERS :: 0
DEFAULT_TEXTURED_FRAGMENT_UNIFORM_BUFFERS :: 0

DEFAULT_TEXTURED_FRAGMENT_TEX :: goose.Texture_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}
DEFAULT_TEXTURED_FRAGMENT_TEX_SAMPLER :: goose.Sampler_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}

DEFAULT_TEXTURED_FRAGMENT_BINDINGS := [2]goose.Binding {
	{name = "tex", stage = .Fragment, kind = .Texture, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "tex_sampler", stage = .Fragment, kind = .Sampler, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
}

default_textured_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "default_textured.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(DEFAULT_TEXTURED_FRAGMENT_CODE), size = len(DEFAULT_TEXTURED_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = DEFAULT_TEXTURED_FRAGMENT_SAMPLERS,
			storage_textures = DEFAULT_TEXTURED_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = DEFAULT_TEXTURED_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = DEFAULT_TEXTURED_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {data = &DEFAULT_TEXTURED_FRAGMENT_BINDINGS[0], count = len(DEFAULT_TEXTURED_FRAGMENT_BINDINGS)},
	}
}

