// Generated by shader/tools/generator. Do not edit.
package shader_tests

import shader ".."

COMPUTE_PIPELINE_COMPUTE_METAL_CODE :: #load("generated/compute_pipeline.compute.msl")
COMPUTE_PIPELINE_COMPUTE_SPIRV_CODE :: #load("generated/compute_pipeline.compute.spv")

COMPUTE_PIPELINE_COMPUTE_SAMPLERS :: 0
COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_TEXTURES :: 0
COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_TEXTURES :: 0
COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_THREAD_COUNT :: [3]u32{8, 4, 1}

Compute_Pipeline_Compute_Compute_Uniforms :: struct #max_field_align(16) {
	scale: f32,
	bias: f32,
	count: u32,
}

#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, scale) == 0)
#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, bias) == 4)
#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, count) == 8)
#assert(size_of(Compute_Pipeline_Compute_Compute_Uniforms) == 12)

Compute_Pipeline_Compute_Uniform_Block :: struct #max_field_align(16) {
	data: Compute_Pipeline_Compute_Compute_Uniforms,
}

#assert(offset_of(Compute_Pipeline_Compute_Uniform_Block, data) == 0)
#assert(size_of(Compute_Pipeline_Compute_Uniform_Block) == 12)

COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SLOT :: 0
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SIZE :: 12

compute_pipeline_compute_push_uniform_block :: proc(command_buffer: ^shader.Command_Buffer, data: ^Compute_Pipeline_Compute_Uniform_Block) {
	shader.push_compute_uniform(command_buffer, COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SLOT, data)
}

compute_pipeline_compute :: proc() -> shader.Compute_Parameters {
	return {
		code = {
			name = "compute_pipeline.compute",
			entrypoint = "computeMain",
			metal = {data = raw_data(COMPUTE_PIPELINE_COMPUTE_METAL_CODE), size = len(COMPUTE_PIPELINE_COMPUTE_METAL_CODE)},
			spirv = {data = raw_data(COMPUTE_PIPELINE_COMPUTE_SPIRV_CODE), size = len(COMPUTE_PIPELINE_COMPUTE_SPIRV_CODE)},
		},
		resources = {
			samplers = COMPUTE_PIPELINE_COMPUTE_SAMPLERS,
			readonly_storage_textures = COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_TEXTURES,
			readonly_storage_buffers = COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_BUFFERS,
			readwrite_storage_textures = COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_TEXTURES,
			readwrite_storage_buffers = COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_BUFFERS,
			uniform_buffers = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BUFFERS,
		},
		thread_count = COMPUTE_PIPELINE_COMPUTE_THREAD_COUNT,
	}
}

