// Generated by shader/tools/generator. Do not edit.
package shader_tests

import shader ".."

GRAPHICS_PIPELINE_VERTEX_METAL_CODE :: #load("generated/graphics_pipeline.vert.msl")
GRAPHICS_PIPELINE_VERTEX_SPIRV_CODE :: #load("generated/graphics_pipeline.vert.spv")

GRAPHICS_PIPELINE_VERTEX_SAMPLERS :: 0
GRAPHICS_PIPELINE_VERTEX_STORAGE_TEXTURES :: 0
GRAPHICS_PIPELINE_VERTEX_STORAGE_BUFFERS :: 0
GRAPHICS_PIPELINE_VERTEX_UNIFORM_BUFFERS :: 0

graphics_pipeline_vertex_attributes :: proc($Vertex: typeid) -> [2]shader.Vertex_Attribute {
	return {
		{location = 0, format = .FLOAT3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .FLOAT4, offset = u32(offset_of(Vertex, color))},
	}
}

graphics_pipeline_vertex :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "graphics_pipeline.vertex",
			entrypoint = "vertexMain",
			metal = {data = raw_data(GRAPHICS_PIPELINE_VERTEX_METAL_CODE), size = len(GRAPHICS_PIPELINE_VERTEX_METAL_CODE)},
			spirv = {data = raw_data(GRAPHICS_PIPELINE_VERTEX_SPIRV_CODE), size = len(GRAPHICS_PIPELINE_VERTEX_SPIRV_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = GRAPHICS_PIPELINE_VERTEX_SAMPLERS,
			storage_textures = GRAPHICS_PIPELINE_VERTEX_STORAGE_TEXTURES,
			storage_buffers = GRAPHICS_PIPELINE_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = GRAPHICS_PIPELINE_VERTEX_UNIFORM_BUFFERS,
		},
	}
}

GRAPHICS_PIPELINE_FRAGMENT_METAL_CODE :: #load("generated/graphics_pipeline.frag.msl")
GRAPHICS_PIPELINE_FRAGMENT_SPIRV_CODE :: #load("generated/graphics_pipeline.frag.spv")

GRAPHICS_PIPELINE_FRAGMENT_SAMPLERS :: 0
GRAPHICS_PIPELINE_FRAGMENT_STORAGE_TEXTURES :: 0
GRAPHICS_PIPELINE_FRAGMENT_STORAGE_BUFFERS :: 0
GRAPHICS_PIPELINE_FRAGMENT_UNIFORM_BUFFERS :: 0

graphics_pipeline_fragment :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "graphics_pipeline.fragment",
			entrypoint = "pixelMain",
			metal = {data = raw_data(GRAPHICS_PIPELINE_FRAGMENT_METAL_CODE), size = len(GRAPHICS_PIPELINE_FRAGMENT_METAL_CODE)},
			spirv = {data = raw_data(GRAPHICS_PIPELINE_FRAGMENT_SPIRV_CODE), size = len(GRAPHICS_PIPELINE_FRAGMENT_SPIRV_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = GRAPHICS_PIPELINE_FRAGMENT_SAMPLERS,
			storage_textures = GRAPHICS_PIPELINE_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = GRAPHICS_PIPELINE_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = GRAPHICS_PIPELINE_FRAGMENT_UNIFORM_BUFFERS,
		},
	}
}

