// Generated by shader/tools/generator. Do not edit.
package shader_tests

import shader ".."

UNIFORMS_VERTEX_METAL_CODE :: #load("generated/uniforms.vert.msl")
UNIFORMS_VERTEX_SPIRV_CODE :: #load("generated/uniforms.vert.spv")

UNIFORMS_VERTEX_SAMPLERS :: 0
UNIFORMS_VERTEX_STORAGE_TEXTURES :: 0
UNIFORMS_VERTEX_STORAGE_BUFFERS :: 0
UNIFORMS_VERTEX_UNIFORM_BUFFERS :: 1

Uniforms_Vertex_Lighting :: struct #max_field_align(16) {
	direction: [3]f32,
	_padding_0: [4]u8,
	intensity: f32,
	_padding_1: [12]u8,
}

#assert(offset_of(Uniforms_Vertex_Lighting, direction) == 0)
#assert(offset_of(Uniforms_Vertex_Lighting, intensity) == 16)
#assert(size_of(Uniforms_Vertex_Lighting) == 32)

Uniforms_Vertex_Scene_Uniforms :: struct #max_field_align(16) {
	view_projection: matrix[4, 4]f32,
	camera_position: [3]f32,
	_padding_0: [4]u8,
	exposure: f32,
	_padding_1: [12]u8,
	lighting: Uniforms_Vertex_Lighting,
}

#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, view_projection) == 0)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, camera_position) == 64)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, exposure) == 80)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, lighting) == 96)
#assert(size_of(Uniforms_Vertex_Scene_Uniforms) == 128)

Uniforms_Vertex_Uniform_Block :: struct #max_field_align(16) {
	data: Uniforms_Vertex_Scene_Uniforms,
}

#assert(offset_of(Uniforms_Vertex_Uniform_Block, data) == 0)
#assert(size_of(Uniforms_Vertex_Uniform_Block) == 128)

UNIFORMS_VERTEX_UNIFORM_BLOCK_SLOT :: 0
UNIFORMS_VERTEX_UNIFORM_BLOCK_SIZE :: 128

uniforms_vertex_push_uniform_block :: proc(command_buffer: ^shader.Command_Buffer, data: ^Uniforms_Vertex_Uniform_Block) {
	shader.push_graphics_uniform(command_buffer, .Vertex, UNIFORMS_VERTEX_UNIFORM_BLOCK_SLOT, data)
}

uniforms_vertex_attributes :: proc($Vertex: typeid) -> [1]shader.Vertex_Attribute {
	return {
		{location = 0, format = .FLOAT3, offset = u32(offset_of(Vertex, position))},
	}
}

uniforms_vertex :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "uniforms.vertex",
			entrypoint = "vertexMain",
			metal = {data = raw_data(UNIFORMS_VERTEX_METAL_CODE), size = len(UNIFORMS_VERTEX_METAL_CODE)},
			spirv = {data = raw_data(UNIFORMS_VERTEX_SPIRV_CODE), size = len(UNIFORMS_VERTEX_SPIRV_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = UNIFORMS_VERTEX_SAMPLERS,
			storage_textures = UNIFORMS_VERTEX_STORAGE_TEXTURES,
			storage_buffers = UNIFORMS_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = UNIFORMS_VERTEX_UNIFORM_BUFFERS,
		},
	}
}

UNIFORMS_FRAGMENT_METAL_CODE :: #load("generated/uniforms.frag.msl")
UNIFORMS_FRAGMENT_SPIRV_CODE :: #load("generated/uniforms.frag.spv")

UNIFORMS_FRAGMENT_SAMPLERS :: 0
UNIFORMS_FRAGMENT_STORAGE_TEXTURES :: 0
UNIFORMS_FRAGMENT_STORAGE_BUFFERS :: 0
UNIFORMS_FRAGMENT_UNIFORM_BUFFERS :: 0

uniforms_fragment :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "uniforms.fragment",
			entrypoint = "pixelMain",
			metal = {data = raw_data(UNIFORMS_FRAGMENT_METAL_CODE), size = len(UNIFORMS_FRAGMENT_METAL_CODE)},
			spirv = {data = raw_data(UNIFORMS_FRAGMENT_SPIRV_CODE), size = len(UNIFORMS_FRAGMENT_SPIRV_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = UNIFORMS_FRAGMENT_SAMPLERS,
			storage_textures = UNIFORMS_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = UNIFORMS_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = UNIFORMS_FRAGMENT_UNIFORM_BUFFERS,
		},
	}
}

