// Generated by shader/tools/generator. Do not edit.
package shader_tests

import shader ".."

VERTEX_BUFFERS_VERTEX_METAL_CODE :: #load("generated/vertex_buffers.vert.msl")
VERTEX_BUFFERS_VERTEX_SPIRV_CODE :: #load("generated/vertex_buffers.vert.spv")

VERTEX_BUFFERS_VERTEX_SAMPLERS :: 0
VERTEX_BUFFERS_VERTEX_STORAGE_TEXTURES :: 0
VERTEX_BUFFERS_VERTEX_STORAGE_BUFFERS :: 0
VERTEX_BUFFERS_VERTEX_UNIFORM_BUFFERS :: 0

vertex_buffers_vertex_attributes :: proc($Vertex: typeid) -> [4]shader.Vertex_Attribute {
	return {
		{location = 0, format = .FLOAT3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .FLOAT3, offset = u32(offset_of(Vertex, normal))},
		{location = 2, format = .FLOAT2, offset = u32(offset_of(Vertex, uv))},
		{location = 3, format = .UINT4, offset = u32(offset_of(Vertex, joints))},
	}
}

vertex_buffers_vertex :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "vertex_buffers.vertex",
			entrypoint = "vertexMain",
			metal = {data = raw_data(VERTEX_BUFFERS_VERTEX_METAL_CODE), size = len(VERTEX_BUFFERS_VERTEX_METAL_CODE)},
			spirv = {data = raw_data(VERTEX_BUFFERS_VERTEX_SPIRV_CODE), size = len(VERTEX_BUFFERS_VERTEX_SPIRV_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = VERTEX_BUFFERS_VERTEX_SAMPLERS,
			storage_textures = VERTEX_BUFFERS_VERTEX_STORAGE_TEXTURES,
			storage_buffers = VERTEX_BUFFERS_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = VERTEX_BUFFERS_VERTEX_UNIFORM_BUFFERS,
		},
	}
}

VERTEX_BUFFERS_FRAGMENT_METAL_CODE :: #load("generated/vertex_buffers.frag.msl")
VERTEX_BUFFERS_FRAGMENT_SPIRV_CODE :: #load("generated/vertex_buffers.frag.spv")

VERTEX_BUFFERS_FRAGMENT_SAMPLERS :: 0
VERTEX_BUFFERS_FRAGMENT_STORAGE_TEXTURES :: 0
VERTEX_BUFFERS_FRAGMENT_STORAGE_BUFFERS :: 0
VERTEX_BUFFERS_FRAGMENT_UNIFORM_BUFFERS :: 0

vertex_buffers_fragment :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "vertex_buffers.fragment",
			entrypoint = "pixelMain",
			metal = {data = raw_data(VERTEX_BUFFERS_FRAGMENT_METAL_CODE), size = len(VERTEX_BUFFERS_FRAGMENT_METAL_CODE)},
			spirv = {data = raw_data(VERTEX_BUFFERS_FRAGMENT_SPIRV_CODE), size = len(VERTEX_BUFFERS_FRAGMENT_SPIRV_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = VERTEX_BUFFERS_FRAGMENT_SAMPLERS,
			storage_textures = VERTEX_BUFFERS_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = VERTEX_BUFFERS_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = VERTEX_BUFFERS_FRAGMENT_UNIFORM_BUFFERS,
		},
	}
}

