// Generated by goose/tools/build. Do not edit.
package shader_parameters

import goose "../goose"

BLUR_COMPUTE_CODE :: #load("../../shaders/generated/blur.compute.msl")

BLUR_COMPUTE_SAMPLERS :: 1
BLUR_COMPUTE_READONLY_STORAGE_TEXTURES :: 0
BLUR_COMPUTE_READONLY_STORAGE_BUFFERS :: 0
BLUR_COMPUTE_READWRITE_STORAGE_TEXTURES :: 1
BLUR_COMPUTE_READWRITE_STORAGE_BUFFERS :: 0
BLUR_COMPUTE_UNIFORM_BUFFERS :: 0
BLUR_COMPUTE_THREAD_COUNT :: [3]u32{8, 8, 1}

BLUR_COMPUTE_INPUT_IMAGE :: goose.Texture_Binding {stage = .Compute, location = {space = 0, binding = 0, slot = 0, count = 1}}
BLUR_COMPUTE_INPUT_SAMPLER :: goose.Sampler_Binding {stage = .Compute, location = {space = 0, binding = 0, slot = 0, count = 1}}
BLUR_COMPUTE_OUTPUT_IMAGE :: goose.Binding {name = "output_image", stage = .Compute, kind = .Storage_Texture, access = .Read_Write, location = {space = 0, binding = 1, slot = 0, count = 1}}

BLUR_COMPUTE_BINDINGS := [3]goose.Binding {
	{name = "input_image", stage = .Compute, kind = .Texture, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "input_sampler", stage = .Compute, kind = .Sampler, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "output_image", stage = .Compute, kind = .Storage_Texture, access = .Read_Write, location = {space = 0, binding = 1, slot = 0, count = 1}},
}

blur_compute :: proc() -> goose.Compute_Parameters {
	return {
		code = {
			name = "blur.compute",
			entrypoint = "computeMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(BLUR_COMPUTE_CODE), size = len(BLUR_COMPUTE_CODE)},
		},
		resources = {
			samplers = BLUR_COMPUTE_SAMPLERS,
			readonly_storage_textures = BLUR_COMPUTE_READONLY_STORAGE_TEXTURES,
			readonly_storage_buffers = BLUR_COMPUTE_READONLY_STORAGE_BUFFERS,
			readwrite_storage_textures = BLUR_COMPUTE_READWRITE_STORAGE_TEXTURES,
			readwrite_storage_buffers = BLUR_COMPUTE_READWRITE_STORAGE_BUFFERS,
			uniform_buffers = BLUR_COMPUTE_UNIFORM_BUFFERS,
		},
		thread_count = BLUR_COMPUTE_THREAD_COUNT,
		bindings = {data = &BLUR_COMPUTE_BINDINGS[0], count = len(BLUR_COMPUTE_BINDINGS)},
	}
}

