// Generated by shader/tools/generator. Do not edit.
package shader_parameters

import shader "../shader"

COMPUTE_METAL_CODE :: #load("../../shaders/generated/compute.msl")
COMPUTE_SPIRV_CODE :: #load("../../shaders/generated/compute.spv")

COMPUTE_SAMPLERS :: 0
COMPUTE_READONLY_STORAGE_TEXTURES :: 0
COMPUTE_READONLY_STORAGE_BUFFERS :: 1
COMPUTE_READWRITE_STORAGE_TEXTURES :: 0
COMPUTE_READWRITE_STORAGE_BUFFERS :: 1
COMPUTE_UNIFORM_BUFFERS :: 0
COMPUTE_THREAD_COUNT :: [3]u32{64, 1, 1}

compute :: proc() -> shader.Compute_Parameters {
	return {
		code = {
			name = "compute.compute",
			entrypoint = "computeMain",
			metal = {data = raw_data(COMPUTE_METAL_CODE), size = len(COMPUTE_METAL_CODE)},
			spirv = {data = raw_data(COMPUTE_SPIRV_CODE), size = len(COMPUTE_SPIRV_CODE)},
		},
		resources = {
			samplers = COMPUTE_SAMPLERS,
			readonly_storage_textures = COMPUTE_READONLY_STORAGE_TEXTURES,
			readonly_storage_buffers = COMPUTE_READONLY_STORAGE_BUFFERS,
			readwrite_storage_textures = COMPUTE_READWRITE_STORAGE_TEXTURES,
			readwrite_storage_buffers = COMPUTE_READWRITE_STORAGE_BUFFERS,
			uniform_buffers = COMPUTE_UNIFORM_BUFFERS,
		},
		thread_count = COMPUTE_THREAD_COUNT,
	}
}

