// Generated by goose/tools/build. Do not edit.
package shader_parameters

import goose "../goose"

COMPUTE_CODE :: #load("../../shaders/generated/compute.compute.msl")

COMPUTE_SAMPLERS :: 0
COMPUTE_READONLY_STORAGE_TEXTURES :: 0
COMPUTE_READONLY_STORAGE_BUFFERS :: 1
COMPUTE_READWRITE_STORAGE_TEXTURES :: 0
COMPUTE_READWRITE_STORAGE_BUFFERS :: 1
COMPUTE_UNIFORM_BUFFERS :: 0
COMPUTE_THREAD_COUNT :: [3]u32{64, 1, 1}

COMPUTE_COMPUTE_INPUT_DATA :: goose.Binding {name = "inputData", stage = .Compute, kind = .Storage_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}}
COMPUTE_COMPUTE_OUTPUT_DATA :: goose.Binding {name = "outputData", stage = .Compute, kind = .Storage_Buffer, access = .Read_Write, location = {space = 0, binding = 1, slot = 0, count = 1}}

COMPUTE_BINDINGS := [2]goose.Binding {
	{name = "inputData", stage = .Compute, kind = .Storage_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "outputData", stage = .Compute, kind = .Storage_Buffer, access = .Read_Write, location = {space = 0, binding = 1, slot = 0, count = 1}},
}

compute :: proc() -> goose.Compute_Parameters {
	return {
		code = {
			name = "compute.compute",
			entrypoint = "computeMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(COMPUTE_CODE), size = len(COMPUTE_CODE)},
		},
		resources = {
			samplers = COMPUTE_SAMPLERS,
			readonly_storage_textures = COMPUTE_READONLY_STORAGE_TEXTURES,
			readonly_storage_buffers = COMPUTE_READONLY_STORAGE_BUFFERS,
			readwrite_storage_textures = COMPUTE_READWRITE_STORAGE_TEXTURES,
			readwrite_storage_buffers = COMPUTE_READWRITE_STORAGE_BUFFERS,
			uniform_buffers = COMPUTE_UNIFORM_BUFFERS,
		},
		thread_count = COMPUTE_THREAD_COUNT,
		bindings = {data = &COMPUTE_BINDINGS[0], count = len(COMPUTE_BINDINGS)},
	}
}

