// Generated by shader/tools/generator. Do not edit.
package shader_parameters

import shader "../shader"

TRIANGLE_VERTEX_METAL_CODE :: #load("../../shaders/generated/triangle.vert.msl")
TRIANGLE_VERTEX_SPIRV_CODE :: #load("../../shaders/generated/triangle.vert.spv")

TRIANGLE_VERTEX_SAMPLERS :: 0
TRIANGLE_VERTEX_STORAGE_TEXTURES :: 0
TRIANGLE_VERTEX_STORAGE_BUFFERS :: 0
TRIANGLE_VERTEX_UNIFORM_BUFFERS :: 1

Triangle_Vertex_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
}

#assert(offset_of(Triangle_Vertex_Uniforms, mvp) == 0)
#assert(size_of(Triangle_Vertex_Uniforms) == 64)

Triangle_Vertex_Uniform_Block :: struct #max_field_align(16) {
	u_data: Triangle_Vertex_Uniforms,
}

#assert(offset_of(Triangle_Vertex_Uniform_Block, u_data) == 0)
#assert(size_of(Triangle_Vertex_Uniform_Block) == 64)

TRIANGLE_VERTEX_UNIFORM_BLOCK_SLOT :: 0
TRIANGLE_VERTEX_UNIFORM_BLOCK_SIZE :: 64

triangle_vertex_push_uniform_block :: proc(command_buffer: ^shader.Command_Buffer, data: ^Triangle_Vertex_Uniform_Block) {
	shader.push_graphics_uniform(command_buffer, .Vertex, TRIANGLE_VERTEX_UNIFORM_BLOCK_SLOT, data)
}

triangle_vertex_attributes :: proc($Vertex: typeid) -> [3]shader.Vertex_Attribute {
	return {
		{location = 0, format = .FLOAT3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .FLOAT4, offset = u32(offset_of(Vertex, color))},
		{location = 2, format = .FLOAT2, offset = u32(offset_of(Vertex, uv))},
	}
}

triangle_vertex :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "triangle.vertex",
			entrypoint = "vertexMain",
			metal = {data = raw_data(TRIANGLE_VERTEX_METAL_CODE), size = len(TRIANGLE_VERTEX_METAL_CODE)},
			spirv = {data = raw_data(TRIANGLE_VERTEX_SPIRV_CODE), size = len(TRIANGLE_VERTEX_SPIRV_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = TRIANGLE_VERTEX_SAMPLERS,
			storage_textures = TRIANGLE_VERTEX_STORAGE_TEXTURES,
			storage_buffers = TRIANGLE_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = TRIANGLE_VERTEX_UNIFORM_BUFFERS,
		},
	}
}

TRIANGLE_FRAGMENT_METAL_CODE :: #load("../../shaders/generated/triangle.frag.msl")
TRIANGLE_FRAGMENT_SPIRV_CODE :: #load("../../shaders/generated/triangle.frag.spv")

TRIANGLE_FRAGMENT_SAMPLERS :: 1
TRIANGLE_FRAGMENT_STORAGE_TEXTURES :: 0
TRIANGLE_FRAGMENT_STORAGE_BUFFERS :: 0
TRIANGLE_FRAGMENT_UNIFORM_BUFFERS :: 0

triangle_fragment :: proc() -> shader.Graphics_Parameters {
	return {
		code = {
			name = "triangle.fragment",
			entrypoint = "pixelMain",
			metal = {data = raw_data(TRIANGLE_FRAGMENT_METAL_CODE), size = len(TRIANGLE_FRAGMENT_METAL_CODE)},
			spirv = {data = raw_data(TRIANGLE_FRAGMENT_SPIRV_CODE), size = len(TRIANGLE_FRAGMENT_SPIRV_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = TRIANGLE_FRAGMENT_SAMPLERS,
			storage_textures = TRIANGLE_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = TRIANGLE_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = TRIANGLE_FRAGMENT_UNIFORM_BUFFERS,
		},
	}
}

