// Generated by goose/tools/build. Do not edit.
package shader_parameters

import goose "../goose"

TRIANGLE_VERTEX_CODE :: #load("../../shaders/generated/triangle.vert.msl")

TRIANGLE_VERTEX_SAMPLERS :: 0
TRIANGLE_VERTEX_STORAGE_TEXTURES :: 0
TRIANGLE_VERTEX_STORAGE_BUFFERS :: 0
TRIANGLE_VERTEX_UNIFORM_BUFFERS :: 1

Triangle_Vertex_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
}

#assert(offset_of(Triangle_Vertex_Uniforms, mvp) == 0)
#assert(size_of(Triangle_Vertex_Uniforms) == 64)

Triangle_Vertex_Uniform_Block :: struct #max_field_align(16) {
	u_data: Triangle_Vertex_Uniforms,
}

#assert(offset_of(Triangle_Vertex_Uniform_Block, u_data) == 0)
#assert(size_of(Triangle_Vertex_Uniform_Block) == 64)

TRIANGLE_VERTEX_UNIFORM_BLOCK_SLOT :: 0
TRIANGLE_VERTEX_UNIFORM_BLOCK_SPACE :: 0
TRIANGLE_VERTEX_UNIFORM_BLOCK_BINDING :: 0
TRIANGLE_VERTEX_UNIFORM_BLOCK_COUNT :: 1
TRIANGLE_VERTEX_UNIFORM_BLOCK_SIZE :: 64
TRIANGLE_VERTEX_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Vertex,
	location = {space = TRIANGLE_VERTEX_UNIFORM_BLOCK_SPACE, binding = TRIANGLE_VERTEX_UNIFORM_BLOCK_BINDING, slot = TRIANGLE_VERTEX_UNIFORM_BLOCK_SLOT, count = TRIANGLE_VERTEX_UNIFORM_BLOCK_COUNT},
	size = TRIANGLE_VERTEX_UNIFORM_BLOCK_SIZE,
}

triangle_vertex_attributes :: proc($Vertex: typeid) -> [3]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .Float4, offset = u32(offset_of(Vertex, color))},
		{location = 2, format = .Float2, offset = u32(offset_of(Vertex, uv))},
	}
}

TRIANGLE_VERTEX_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Vertex, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 64},
}

triangle_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "triangle.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(TRIANGLE_VERTEX_CODE), size = len(TRIANGLE_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = TRIANGLE_VERTEX_SAMPLERS,
			storage_textures = TRIANGLE_VERTEX_STORAGE_TEXTURES,
			storage_buffers = TRIANGLE_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = TRIANGLE_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {data = &TRIANGLE_VERTEX_BINDINGS[0], count = len(TRIANGLE_VERTEX_BINDINGS)},
	}
}

TRIANGLE_FRAGMENT_CODE :: #load("../../shaders/generated/triangle.frag.msl")

TRIANGLE_FRAGMENT_SAMPLERS :: 1
TRIANGLE_FRAGMENT_STORAGE_TEXTURES :: 0
TRIANGLE_FRAGMENT_STORAGE_BUFFERS :: 0
TRIANGLE_FRAGMENT_UNIFORM_BUFFERS :: 0

TRIANGLE_FRAGMENT_TEX :: goose.Texture_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}
TRIANGLE_FRAGMENT_TEX_SAMPLER :: goose.Sampler_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}

TRIANGLE_FRAGMENT_BINDINGS := [2]goose.Binding {
	{name = "tex", stage = .Fragment, kind = .Texture, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "tex_sampler", stage = .Fragment, kind = .Sampler, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
}

triangle_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "triangle.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(TRIANGLE_FRAGMENT_CODE), size = len(TRIANGLE_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = TRIANGLE_FRAGMENT_SAMPLERS,
			storage_textures = TRIANGLE_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = TRIANGLE_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = TRIANGLE_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {data = &TRIANGLE_FRAGMENT_BINDINGS[0], count = len(TRIANGLE_FRAGMENT_BINDINGS)},
	}
}

