// Generated by goose/tools/build. Do not edit.
package shader_parameters

import goose "../goose"

UNLIT_COLOR_VERTEX_CODE :: #load("../../shaders/generated/unlit_color.vert.msl")

UNLIT_COLOR_VERTEX_SAMPLERS :: 0
UNLIT_COLOR_VERTEX_STORAGE_TEXTURES :: 0
UNLIT_COLOR_VERTEX_STORAGE_BUFFERS :: 0
UNLIT_COLOR_VERTEX_UNIFORM_BUFFERS :: 1

Unlit_Color_Vertex_Unlit_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
	tint: [4]f32,
}

#assert(offset_of(Unlit_Color_Vertex_Unlit_Uniforms, mvp) == 0)
#assert(offset_of(Unlit_Color_Vertex_Unlit_Uniforms, tint) == 64)
#assert(size_of(Unlit_Color_Vertex_Unlit_Uniforms) == 80)

Unlit_Color_Vertex_Uniform_Block :: struct #max_field_align(16) {
	data: Unlit_Color_Vertex_Unlit_Uniforms,
}

#assert(offset_of(Unlit_Color_Vertex_Uniform_Block, data) == 0)
#assert(size_of(Unlit_Color_Vertex_Uniform_Block) == 80)

UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SLOT :: 0
UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SPACE :: 0
UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_BINDING :: 0
UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_COUNT :: 1
UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SIZE :: 80
UNLIT_COLOR_VERTEX_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Vertex,
	location = {space = UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SPACE, binding = UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_BINDING, slot = UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SLOT, count = UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_COUNT},
	size = UNLIT_COLOR_VERTEX_UNIFORM_BLOCK_SIZE,
}

unlit_color_vertex_attributes :: proc($Vertex: typeid) -> [1]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
	}
}

UNLIT_COLOR_VERTEX_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Vertex, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 80},
}

unlit_color_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "unlit_color.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(UNLIT_COLOR_VERTEX_CODE), size = len(UNLIT_COLOR_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = UNLIT_COLOR_VERTEX_SAMPLERS,
			storage_textures = UNLIT_COLOR_VERTEX_STORAGE_TEXTURES,
			storage_buffers = UNLIT_COLOR_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = UNLIT_COLOR_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {data = &UNLIT_COLOR_VERTEX_BINDINGS[0], count = len(UNLIT_COLOR_VERTEX_BINDINGS)},
	}
}

UNLIT_COLOR_FRAGMENT_CODE :: #load("../../shaders/generated/unlit_color.frag.msl")

UNLIT_COLOR_FRAGMENT_SAMPLERS :: 0
UNLIT_COLOR_FRAGMENT_STORAGE_TEXTURES :: 0
UNLIT_COLOR_FRAGMENT_STORAGE_BUFFERS :: 0
UNLIT_COLOR_FRAGMENT_UNIFORM_BUFFERS :: 1

Unlit_Color_Fragment_Unlit_Uniforms :: struct #max_field_align(16) {
	mvp: matrix[4, 4]f32,
	tint: [4]f32,
}

#assert(offset_of(Unlit_Color_Fragment_Unlit_Uniforms, mvp) == 0)
#assert(offset_of(Unlit_Color_Fragment_Unlit_Uniforms, tint) == 64)
#assert(size_of(Unlit_Color_Fragment_Unlit_Uniforms) == 80)

Unlit_Color_Fragment_Uniform_Block :: struct #max_field_align(16) {
	data: Unlit_Color_Fragment_Unlit_Uniforms,
}

#assert(offset_of(Unlit_Color_Fragment_Uniform_Block, data) == 0)
#assert(size_of(Unlit_Color_Fragment_Uniform_Block) == 80)

UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SLOT :: 0
UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SPACE :: 0
UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_BINDING :: 0
UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_COUNT :: 1
UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SIZE :: 80
UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Fragment,
	location = {space = UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SPACE, binding = UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_BINDING, slot = UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SLOT, count = UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_COUNT},
	size = UNLIT_COLOR_FRAGMENT_UNIFORM_BLOCK_SIZE,
}

UNLIT_COLOR_FRAGMENT_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Fragment, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 80},
}

unlit_color_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "unlit_color.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(UNLIT_COLOR_FRAGMENT_CODE), size = len(UNLIT_COLOR_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = UNLIT_COLOR_FRAGMENT_SAMPLERS,
			storage_textures = UNLIT_COLOR_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = UNLIT_COLOR_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = UNLIT_COLOR_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {data = &UNLIT_COLOR_FRAGMENT_BINDINGS[0], count = len(UNLIT_COLOR_FRAGMENT_BINDINGS)},
	}
}

