// Generated by goose/tools/build. Do not edit.
package goose_tests

import goose ".."

COMPUTE_PIPELINE_COMPUTE_CODE :: #load("generated/compute_pipeline.compute.msl")

COMPUTE_PIPELINE_COMPUTE_SAMPLERS :: 0
COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_TEXTURES :: 0
COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_TEXTURES :: 0
COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BUFFERS :: 1
COMPUTE_PIPELINE_COMPUTE_THREAD_COUNT :: [3]u32{8, 4, 1}

Compute_Pipeline_Compute_Compute_Uniforms :: struct #max_field_align(16) {
	scale: f32,
	bias: f32,
	count: u32,
}

#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, scale) == 0)
#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, bias) == 4)
#assert(offset_of(Compute_Pipeline_Compute_Compute_Uniforms, count) == 8)
#assert(size_of(Compute_Pipeline_Compute_Compute_Uniforms) == 12)

Compute_Pipeline_Compute_Uniform_Block :: struct #max_field_align(16) {
	data: Compute_Pipeline_Compute_Compute_Uniforms,
}

#assert(offset_of(Compute_Pipeline_Compute_Uniform_Block, data) == 0)
#assert(size_of(Compute_Pipeline_Compute_Uniform_Block) == 12)

COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SLOT :: 0
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SPACE :: 0
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_BINDING :: 0
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_COUNT :: 1
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SIZE :: 12
COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Compute,
	location = {space = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SPACE, binding = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_BINDING, slot = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SLOT, count = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_COUNT},
	size = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BLOCK_SIZE,
}

COMPUTE_PIPELINE_COMPUTE_INPUT_DATA :: goose.Binding {name = "input_data", stage = .Compute, kind = .Storage_Buffer, access = .Read_Only, location = {space = 0, binding = 1, slot = 0, count = 1}}
COMPUTE_PIPELINE_COMPUTE_OUTPUT_DATA :: goose.Binding {name = "output_data", stage = .Compute, kind = .Storage_Buffer, access = .Read_Write, location = {space = 0, binding = 2, slot = 0, count = 1}}

COMPUTE_PIPELINE_COMPUTE_BINDINGS := [3]goose.Binding {
	{name = "UniformBlock", stage = .Compute, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 12},
	{name = "input_data", stage = .Compute, kind = .Storage_Buffer, access = .Read_Only, location = {space = 0, binding = 1, slot = 0, count = 1}},
	{name = "output_data", stage = .Compute, kind = .Storage_Buffer, access = .Read_Write, location = {space = 0, binding = 2, slot = 0, count = 1}},
}

compute_pipeline_compute :: proc() -> goose.Compute_Parameters {
	return {
		code = {
			name = "compute_pipeline.compute",
			entrypoint = "computeMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(COMPUTE_PIPELINE_COMPUTE_CODE), size = len(COMPUTE_PIPELINE_COMPUTE_CODE)},
		},
		resources = {
			samplers = COMPUTE_PIPELINE_COMPUTE_SAMPLERS,
			readonly_storage_textures = COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_TEXTURES,
			readonly_storage_buffers = COMPUTE_PIPELINE_COMPUTE_READONLY_STORAGE_BUFFERS,
			readwrite_storage_textures = COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_TEXTURES,
			readwrite_storage_buffers = COMPUTE_PIPELINE_COMPUTE_READWRITE_STORAGE_BUFFERS,
			uniform_buffers = COMPUTE_PIPELINE_COMPUTE_UNIFORM_BUFFERS,
		},
		thread_count = COMPUTE_PIPELINE_COMPUTE_THREAD_COUNT,
		bindings = {data = &COMPUTE_PIPELINE_COMPUTE_BINDINGS[0], count = len(COMPUTE_PIPELINE_COMPUTE_BINDINGS)},
	}
}

