// Generated by goose/tools/build. Do not edit.
package goose_tests

import goose ".."

GRAPHICS_PIPELINE_VERTEX_CODE :: #load("generated/graphics_pipeline.vert.msl")

GRAPHICS_PIPELINE_VERTEX_SAMPLERS :: 0
GRAPHICS_PIPELINE_VERTEX_STORAGE_TEXTURES :: 0
GRAPHICS_PIPELINE_VERTEX_STORAGE_BUFFERS :: 0
GRAPHICS_PIPELINE_VERTEX_UNIFORM_BUFFERS :: 0

graphics_pipeline_vertex_attributes :: proc($Vertex: typeid) -> [2]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .Float4, offset = u32(offset_of(Vertex, color))},
	}
}

graphics_pipeline_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "graphics_pipeline.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(GRAPHICS_PIPELINE_VERTEX_CODE), size = len(GRAPHICS_PIPELINE_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = GRAPHICS_PIPELINE_VERTEX_SAMPLERS,
			storage_textures = GRAPHICS_PIPELINE_VERTEX_STORAGE_TEXTURES,
			storage_buffers = GRAPHICS_PIPELINE_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = GRAPHICS_PIPELINE_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {},
	}
}

GRAPHICS_PIPELINE_FRAGMENT_CODE :: #load("generated/graphics_pipeline.frag.msl")

GRAPHICS_PIPELINE_FRAGMENT_SAMPLERS :: 1
GRAPHICS_PIPELINE_FRAGMENT_STORAGE_TEXTURES :: 0
GRAPHICS_PIPELINE_FRAGMENT_STORAGE_BUFFERS :: 0
GRAPHICS_PIPELINE_FRAGMENT_UNIFORM_BUFFERS :: 0

GRAPHICS_PIPELINE_FRAGMENT_TEX :: goose.Texture_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}
GRAPHICS_PIPELINE_FRAGMENT_TEX_SAMPLER :: goose.Sampler_Binding {stage = .Fragment, location = {space = 0, binding = 0, slot = 0, count = 1}}

GRAPHICS_PIPELINE_FRAGMENT_BINDINGS := [2]goose.Binding {
	{name = "tex", stage = .Fragment, kind = .Texture, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
	{name = "tex_sampler", stage = .Fragment, kind = .Sampler, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}},
}

graphics_pipeline_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "graphics_pipeline.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(GRAPHICS_PIPELINE_FRAGMENT_CODE), size = len(GRAPHICS_PIPELINE_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = GRAPHICS_PIPELINE_FRAGMENT_SAMPLERS,
			storage_textures = GRAPHICS_PIPELINE_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = GRAPHICS_PIPELINE_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = GRAPHICS_PIPELINE_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {data = &GRAPHICS_PIPELINE_FRAGMENT_BINDINGS[0], count = len(GRAPHICS_PIPELINE_FRAGMENT_BINDINGS)},
	}
}

