// Generated by goose/tools/build. Do not edit.
package goose_tests

import goose ".."

UNIFORMS_VERTEX_CODE :: #load("generated/uniforms.vert.msl")

UNIFORMS_VERTEX_SAMPLERS :: 0
UNIFORMS_VERTEX_STORAGE_TEXTURES :: 0
UNIFORMS_VERTEX_STORAGE_BUFFERS :: 0
UNIFORMS_VERTEX_UNIFORM_BUFFERS :: 1

Uniforms_Vertex_Lighting :: struct #max_field_align(16) {
	direction: [3]f32,
	_padding_0: [4]u8,
	intensity: f32,
	_padding_1: [12]u8,
}

#assert(offset_of(Uniforms_Vertex_Lighting, direction) == 0)
#assert(offset_of(Uniforms_Vertex_Lighting, intensity) == 16)
#assert(size_of(Uniforms_Vertex_Lighting) == 32)

Uniforms_Vertex_Scene_Uniforms :: struct #max_field_align(16) {
	view_projection: matrix[4, 4]f32,
	camera_position: [3]f32,
	_padding_0: [4]u8,
	exposure: f32,
	_padding_1: [12]u8,
	lighting: Uniforms_Vertex_Lighting,
	half_values: [2]f16,
	_padding_2: [4]u8,
	indices: [2]i32,
	flags: [4]u32,
	enabled: bool,
	_padding_3: [15]u8,
	palette: [3][4]f32,
	weights: [4]f32,
}

#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, view_projection) == 0)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, camera_position) == 64)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, exposure) == 80)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, lighting) == 96)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, half_values) == 128)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, indices) == 136)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, flags) == 144)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, enabled) == 160)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, palette) == 176)
#assert(offset_of(Uniforms_Vertex_Scene_Uniforms, weights) == 224)
#assert(size_of(Uniforms_Vertex_Scene_Uniforms) == 240)

Uniforms_Vertex_Uniform_Block :: struct #max_field_align(16) {
	data: Uniforms_Vertex_Scene_Uniforms,
}

#assert(offset_of(Uniforms_Vertex_Uniform_Block, data) == 0)
#assert(size_of(Uniforms_Vertex_Uniform_Block) == 240)

UNIFORMS_VERTEX_UNIFORM_BLOCK_SLOT :: 0
UNIFORMS_VERTEX_UNIFORM_BLOCK_SPACE :: 0
UNIFORMS_VERTEX_UNIFORM_BLOCK_BINDING :: 0
UNIFORMS_VERTEX_UNIFORM_BLOCK_COUNT :: 1
UNIFORMS_VERTEX_UNIFORM_BLOCK_SIZE :: 240
UNIFORMS_VERTEX_UNIFORM_BLOCK :: goose.Uniform_Block {
	stage = .Vertex,
	location = {space = UNIFORMS_VERTEX_UNIFORM_BLOCK_SPACE, binding = UNIFORMS_VERTEX_UNIFORM_BLOCK_BINDING, slot = UNIFORMS_VERTEX_UNIFORM_BLOCK_SLOT, count = UNIFORMS_VERTEX_UNIFORM_BLOCK_COUNT},
	size = UNIFORMS_VERTEX_UNIFORM_BLOCK_SIZE,
}

uniforms_vertex_attributes :: proc($Vertex: typeid) -> [1]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
	}
}

UNIFORMS_VERTEX_BINDINGS := [1]goose.Binding {
	{name = "UniformBlock", stage = .Vertex, kind = .Uniform_Buffer, access = .Read_Only, location = {space = 0, binding = 0, slot = 0, count = 1}, size = 240},
}

uniforms_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "uniforms.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(UNIFORMS_VERTEX_CODE), size = len(UNIFORMS_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = UNIFORMS_VERTEX_SAMPLERS,
			storage_textures = UNIFORMS_VERTEX_STORAGE_TEXTURES,
			storage_buffers = UNIFORMS_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = UNIFORMS_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {data = &UNIFORMS_VERTEX_BINDINGS[0], count = len(UNIFORMS_VERTEX_BINDINGS)},
	}
}

UNIFORMS_FRAGMENT_CODE :: #load("generated/uniforms.frag.msl")

UNIFORMS_FRAGMENT_SAMPLERS :: 0
UNIFORMS_FRAGMENT_STORAGE_TEXTURES :: 0
UNIFORMS_FRAGMENT_STORAGE_BUFFERS :: 0
UNIFORMS_FRAGMENT_UNIFORM_BUFFERS :: 0

uniforms_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "uniforms.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(UNIFORMS_FRAGMENT_CODE), size = len(UNIFORMS_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = UNIFORMS_FRAGMENT_SAMPLERS,
			storage_textures = UNIFORMS_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = UNIFORMS_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = UNIFORMS_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {},
	}
}

