// Generated by goose/tools/build. Do not edit.
package goose_tests

import goose ".."

VERTEX_BUFFERS_VERTEX_CODE :: #load("generated/vertex_buffers.vert.msl")

VERTEX_BUFFERS_VERTEX_SAMPLERS :: 0
VERTEX_BUFFERS_VERTEX_STORAGE_TEXTURES :: 0
VERTEX_BUFFERS_VERTEX_STORAGE_BUFFERS :: 0
VERTEX_BUFFERS_VERTEX_UNIFORM_BUFFERS :: 0

vertex_buffers_vertex_attributes :: proc($Vertex: typeid) -> [7]goose.Vertex_Attribute {
	return {
		{location = 0, format = .Float3, offset = u32(offset_of(Vertex, position))},
		{location = 1, format = .Float3, offset = u32(offset_of(Vertex, normal))},
		{location = 2, format = .Float2, offset = u32(offset_of(Vertex, uv))},
		{location = 3, format = .Uint4, offset = u32(offset_of(Vertex, joints))},
		{location = 4, format = .Float16x2, offset = u32(offset_of(Vertex, weights))},
		{location = 5, format = .Uint16x4, offset = u32(offset_of(Vertex, bone_indices))},
		{location = 6, format = .Uint8x4, offset = u32(offset_of(Vertex, flags))},
	}
}

vertex_buffers_vertex :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "vertex_buffers.vertex",
			entrypoint = "vertexMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(VERTEX_BUFFERS_VERTEX_CODE), size = len(VERTEX_BUFFERS_VERTEX_CODE)},
		},
		stage = .Vertex,
		resources = {
			samplers = VERTEX_BUFFERS_VERTEX_SAMPLERS,
			storage_textures = VERTEX_BUFFERS_VERTEX_STORAGE_TEXTURES,
			storage_buffers = VERTEX_BUFFERS_VERTEX_STORAGE_BUFFERS,
			uniform_buffers = VERTEX_BUFFERS_VERTEX_UNIFORM_BUFFERS,
		},
		bindings = {},
	}
}

VERTEX_BUFFERS_FRAGMENT_CODE :: #load("generated/vertex_buffers.frag.msl")

VERTEX_BUFFERS_FRAGMENT_SAMPLERS :: 0
VERTEX_BUFFERS_FRAGMENT_STORAGE_TEXTURES :: 0
VERTEX_BUFFERS_FRAGMENT_STORAGE_BUFFERS :: 0
VERTEX_BUFFERS_FRAGMENT_UNIFORM_BUFFERS :: 0

vertex_buffers_fragment :: proc() -> goose.Graphics_Parameters {
	return {
		code = {
			name = "vertex_buffers.fragment",
			entrypoint = "pixelMain",
			platform = .Metal,
			format = .Metal_Source,
			blob = {data = raw_data(VERTEX_BUFFERS_FRAGMENT_CODE), size = len(VERTEX_BUFFERS_FRAGMENT_CODE)},
		},
		stage = .Fragment,
		resources = {
			samplers = VERTEX_BUFFERS_FRAGMENT_SAMPLERS,
			storage_textures = VERTEX_BUFFERS_FRAGMENT_STORAGE_TEXTURES,
			storage_buffers = VERTEX_BUFFERS_FRAGMENT_STORAGE_BUFFERS,
			uniform_buffers = VERTEX_BUFFERS_FRAGMENT_UNIFORM_BUFFERS,
		},
		bindings = {},
	}
}

